### ISSUE TITLE
Kobo Libra 2 + 8BitDo Zero 2 gamepad not working for me.

### ISSUE THREAD

**Issue by spkuehl** [tsowell/kobo-btpt#6]
I have a Kobo Libra 2 and an 8BitDo Zero 2 gamepad. I followed the instructions and everything seems fine. I like how easy this has been to install, but it's not working though, any idea on how to debug this or where I could have went wrong? Tried twice.

Kobo Libra 2 version: 4.38.21908
8BitDo Zero 2 version: 1.06

**Comment by tsowell** [comment]
Check the logs for lines containing "BluetoothPageTurner". You should at least see some messages there if it's running, and if you're lucky some of them might be helpful.

**Comment by spkuehl** [comment]
I factory reset my kobo and tried to reinstall the package but same problem. How do I find the logs?

I see the file in "My Books" which seems odd.

![IMG_3330](https://github.com/tsowell/kobo-btpt/assets/8636697/591624ed-8034-4db8-b96c-d645f8764e55)

Same thing with the uninstall file. It doesnt seems to work.

![IMG_3331](https://github.com/tsowell/kobo-btpt/assets/8636697/6e8a0fd0-7204-417c-b375-7cc0b1101290)

**Comment by spkuehl** [comment]
I take it all back! I tried one more time and it is working. Thanks you! It seems like this time I created the files by hand in VIM and pasted them over to my device. That may have helped, or just technology being wierd and eventually it all clicked.

**Comment by tsowell** [comment]
Thanks for the update, I’m glad you got it working!

**Comment by pgaskin** [comment]
You weren't using TextEdit on macOS, we're you, @spkuehl? If so, you need to put it in plain text mode.

**Comment by spkuehl** [comment]
Yeah first time I pulled the file straight from the repo, I also tried through text edit. Vim did the trick in the end.
